### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by miyaki2003** [miyaki2003/Minimum-Viable-Product#15]
概要

実装予定の機能
- [] LINEメッセージ機能
- [] カレンダー機能
- [] ログイン機能

必要なページ
- [] トップページ
- [] ログインページ
- [] カレンダーページ
- [] LINE追加ページ
- [] 設定ページ
- [] イベント作成ページ
- [] イベント詳細ページ
- [] イベント編集ページ

**Comment by kenchasonakai** [comment]
ご提出頂いているissueの形式をご確認後再度ご提出お願いします
下記のような形式になってしまっています
`https://github.com/miyaki2003/Minimum-Viable-Product/issues/15/issues`

**Comment by Tsuchiya2** [comment]
Projectsをクリックして、看板・issue・ストーリーポイントを確認できませんでした。
カリキュラムを参考に対応＆閲覧できる状態への対応をお願いいたします。」

![スクリーンショット 2024-02-25 14 35 56](https://github.com/miyaki2003/Minimum-Viable-Product/assets/61481161/775f765c-5da4-408f-bd0e-abcd6ecf3054)

**Comment by miyaki2003** [comment]
Projectsを設定しました

**Comment by takyyk** [comment]
Projectの設定が確認できないため、再度ご確認お願いします！

**Comment by miyaki2003** [comment]
申し訳ありません。公開しました。

**Comment by kenchasonakai** [comment]
8・13といったストーリポイントが大きいものがあるので、どう実装すればいいのか調べてissueを分解して最低でも5、大半のものが3以下になるようにしましょう

**Comment by Tsuchiya2** [comment]
> 8・13といったストーリポイントが大きいものがあるので、どう実装すればいいのか調べてissueを分解して最低でも5、大半のものが3以下になるようにしましょう

↑のコメントが最後のようですが...何か対応されたのでしょうか。状況が分からないため、一度差し戻しさせていただきます。

**Comment by kenchasonakai** [comment]
LGTMです！
