### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by miyaki2003** [miyaki2003/Minimum-Viable-Product#54]
## 各種情報
サービス名
ReminderChat
サービスURL
https://reminder-chat-38cf4e1a3ae9.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [X] LINEログイン
- [X] Fullcalendar
- [X] カレンダーLINE通知
- [X] LINEbot
- [X] イベント作成
- [X] イベント詳細
- [ ] イベント編集
- [ ] 設定ページ
- [ ] トップページ

トップページ、設定ページ、イベント編集は本リリースで実装します

## READMEレビュー時から変更した機能

simplecalendar→fullcalendarに変更　fullcalendarの方が高度な機能を使用できるため
イベント追加、詳細機能　画面遷移→モーダルに変更　ユーザーがイベント追加をスムーズに行えるため

## サービスイメージがわかるようなスクリーンショット等
![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/089dc4d9-bd54-49b1-8388-77b2f7595910)
月ボタン:　月カレンダーを表示します
リスト:　カレンダーに記載した予定がリストで表示されます
設定ボタン:　本リリースで実装
LINEボタン:　LINEへ遷移します
今日ボタン:　今日の日付に戻ります
カレンダーボタン:　本リリースで実装します

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/56fe2108-91ce-4e05-9727-16d4d679195c)
日付をクリックすると予定が追加できます
通知時間はON　OFFで切り替えられ、現在より未来の時間で設定するとLINE通知します

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/2d7e1f31-0fa5-45d6-88ee-38300c0805c0)
イベントをクリックすると詳細ページが表示されます
削除ボタン:　予定を削除します
編集ボタン:　本リリースで実装します

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/1f86dd8a-be8c-461d-a8b2-9dc7f8795733)
LINEbotはタイトル、通知時間を記載すると設定した時間にリマインドされます

以下の文字を送信するとコマンドとして機能します
キャンセル:　リマインド設定をキャンセル
今日:　今日の日付を送信
一覧:　一覧が現在から時間が近い順に最大10件表示
取り消し:　1つ前のリマインド設定を削除

自然言語は以下のように設定しています
今日　明日　明後日　今週　来週　再来週　今月　来月　再来月　半　午前　午後　朝　X月X日　X/X　X曜日

使用例
今日 14時
明日
今週の金曜
来週の水曜日午後5時半
5月25日10時50分
1/25 6:00
来月13日　１５時２０分
7時15分
10分後
1時間半後
2日後

指定していない時間がある場合はデフォルトで6時0分に設定されます
時間のみの場合は今日の日付として認識します
来月のみの場合は1日6時0分に設定されます

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下確認いただけますでしょうか。

---

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/61481161/db2eb7ca-d6d8-4adf-b035-7dcd46b80c86)

・LINEログイン後、テストというデータが存在している（まだ登録前なのですが...何が表示されてしまっているのでしょうか）
・予定を登録しようとすると、 http://localhost:3000/ に遷移してしまうのですが...イベント登録はどのように行えるのかを確認いただけますでしょうか。（他の箇所でも http://localhost:3000/ に飛ばされる箇所があったので、そちらも合わせてご確認ください）

**Comment by miyaki2003** [comment]
ご確認いただきありがとうございます。

・LINEログイン後、テストというデータが存在している
    開発用で提出してしまったため再提出しました。

・予定を登録しようとすると、 http://localhost:3000/ に遷移
    http://localhost:3000/ は仮のリダイレクト先として使用していました。本リリースで実装を予定しています。

・イベント登録はどのように行えるのか
　カレンダーの画面(日付のマスの部分)を直接クリックしていただけるとイベント登録が行えます。
　イベント詳細画面は追加したイベントのタイトル名を直接クリックしてください。

**Comment by tarakish** [comment]
> ・予定を登録しようとすると、 http://localhost:3000/ に遷移
　http://localhost:3000/ は仮のリダイレクト先として使用していました。本リリースで実装を予定しています。

こちら仮のリダイレクト先に関しては、localhostではなく'https://reminder-chat-38cf4e1a3ae9.herokuapp.com/#'などに遷移するように修正をお願いします。

**Comment by miyaki2003** [comment]
リダイレクト先はコメントアウトで修正しました。

**Comment by kenchasonakai** [comment]
LGTMです！
