### ISSUE TITLE
アプリの不具合

### ISSUE THREAD

**Issue by miyaki2003** [miyaki2003/Minimum-Viable-Product#78]
カレンダーのイベントの通知時間を変更してupdateしたとき、変更前の通知時間と変更後の通知時間の両方が通知されてしまいます

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/540c6fe3-172e-4af6-a059-437679dfe17c)

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/6155c535-b3a3-4ef5-b931-a50ffb91963e)

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/bbc46235-0163-4d13-9c33-e0ef241834be)

イベントを編集し、通知時間を変更
app/jobs/Notification_job.rbのcancelメソッドが呼び出されますが、job = scheduled_set.find { |j| j.jid == job_id }で一致するジョブIDが見つからない
その結果、変更前の通知ジョブが削除されず、新しい通知ジョブが追加されるため、両方の時間に通知が送信されてしまいます
以下のログを確認しました

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/74f29bad-ecd6-46aa-95f3-ccd1cd273847)

![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/50eb64ee-0f9b-4857-8743-4ce6adaa46b2)

NotificationJob.setで@event.notify_timeの通知時間に通知することを設定しています
![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/60fa1832-5657-4ff8-98e1-645c3f508247)

Sidekiq::ScheduledSet.newで時間指定されたジョブを取得できます
![image](https://github.com/miyaki2003/Minimum-Viable-Product/assets/139937818/e54beaf6-b380-45d7-b11d-8b316420a899)

**Comment by kenchasonakai** [comment]
` job_id`はどこかに保存してありますか？

また、コードはスクリーンショットではなく

**Comment by kenchasonakai** [comment]
参照しにくいのでコードの共有はスクリーンショットではなくコードブロックで書くようにお願いします。

```
code block
```

**Comment by kenchasonakai** [comment]
Sidekiqでジョブを登録したり消したりしたことがないのでそもそもやりたいことが出来るのかがわからないですが、

まずはとりあえずSidekiqで実行予定のジョブの一覧を取得して自分がデータベースに保存しているjobのidと一致するjobがあるか確認してみるといいかもです

**Comment by miyaki2003** [comment]
解決しました！
ありがとうございます！
